In [2]:
with open('SMSSpamCollection.txt','r') as file:
    data = file.read()

In [3]:
# len(data)

In [4]:
# data[1]
len(data)

477907

In [5]:
# data.split('\n')

In [6]:
# data[0]

In [7]:
email_ls = data.split('\n')
email_ls

['ham\tGo until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
 'ham\tOk lar... Joking wif u oni...',
 "spam\tFree entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
 'ham\tU dun say so early hor... U c already then say...',
 "ham\tNah I don't think he goes to usf, he lives around here though",
 "spam\tFreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
 'ham\tEven my brother is not like to speak with me. They treat me like aids patent.',
 "ham\tAs per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune",
 'spam\tWINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. 

In [8]:
# x = []
# y = []


# label_email = email_ls[1].split('\t')
# x.append(label_email[1])
# y.append(label_email[0])

In [9]:
x = []
y = []

for line in email_ls:
    email_with_labels = line.split('\t')
    if len( email_with_labels) == 2:
        x.append(email_with_labels[1])
        y.append(email_with_labels[0])

In [10]:
len(x) ,len(y)

(5574, 5574)

In [11]:
x[10]

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [12]:
y[10]

'ham'

In [13]:
## model traing 

import re 

In [14]:
# ls =  "hii Am from @jodhpur and pin code 306114"
# re.sub('[^a-zA-z ]','',ls).lower()

In [15]:
for i in range (len(x)):
    x[i] = re.sub('[^a-zA-z ]','',x[i]).lower()

In [16]:
x[21]

'im going to try for  months ha ha only joking'

In [17]:
import pandas as pd
dt = {"email_message":x,"label":y}
df = pd.DataFrame(dt)
df.head()

email_message label
0  go until jurong point crazy available only in ...   ham
1                            ok lar joking wif u oni   ham
2  free entry in  a wkly comp to win fa cup final...  spam
3        u dun say so early hor u c already then say   ham
4  nah i dont think he goes to usf he lives aroun...   ham

In [18]:
df['label'].value_counts()
#balance data imblanced

ham     4827
spam     747
Name: label, dtype: int64

In [19]:
ham = df[df['label']=='ham']
spam = df[df['label']=='spam']

In [20]:
ham.shape

(4827, 2)

In [21]:
ham.sample(1000).shape

(1000, 2)

In [22]:
# !pip install imblearn     --->>>>>>>>> for the balanced data 
from imblearn.over_sampling import SMOTE  #('synthetic minority over sampling techique')

In [23]:
smote = SMOTE()

In [24]:
x = df['email_message']
y = df['label']

In [25]:
# X,Y = smote.fit_resample(x,y)

In [26]:
ham = ham.sample(1000)

In [27]:
balance_df = pd.concat([ham,spam])

In [28]:
balance_df['label'].value_counts()

ham     1000
spam     747
Name: label, dtype: int64

In [29]:
x = balance_df['email_message']
y = balance_df['label']

In [30]:
# email message transform into numerical


from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [31]:
bow = CountVectorizer(max_features=1700,stop_words='english')

In [32]:
x = bow.fit_transform(x).toarray()

In [33]:
x.shape

(1747, 1700)

In [38]:
column_name = bow.get_feature_names_out()

In [39]:
testing  = pd.DataFrame(x,columns = column_name)






# feature rep,vector rep,embedding rep

In [40]:
pd.set_option('display.max_row',None)

In [41]:
testing

aathilove  able  abt  abta  ac  academic  access  accident  account  \
0             0     0    0     0   0         0       0         0        0   
1             0     0    0     0   0         0       0         0        0   
2             0     0    0     0   0         0       0         0        0   
3             0     0    0     0   0         0       0         0        0   
4             0     0    0     0   0         0       0         0        0   
5             0     0    0     0   0         0       0         0        0   
6             0     0    0     0   0         0       0         0        0   
7             0     0    0     0   0         0       0         0        0   
8             0     0    0     0   0         0       0         0        0   
9             0     0    0     0   0         0       0         0        0   
10            0     0    0     0   0         0       0         0        0   
11            0     0    0     0   0         0       0         0        0   
12            0     0    0     0   0         0       0         0        0   
13            0     0    0     0   0         0       0         0        0   
14            0     0    0     0   0         0       0         0        0   
15            0     0    0     0   0         0       0         0        0   
16            0     0    0     0   0         0       0         0        0   
17            0     0    0     0   0         0       0         0        0   
18            0     0    0     0   0         0       0         0        0   
19            0     0    0     0   0         0       0         0        0   
20            0     0    0     0   0         0       0         0        0   
21            0     0    0     0   0         0       0         0        0   
22            0     0    0     0   0         0       0         0        0   
23            0     0    0     0   0         0       0         0        0   
24            0     0    0     0   0         0       0         0        0   
25            0     0    0     0   0         0       0         0        0   
26            0     0    0     0   0         0       0         0        0   
27            0     0    0     0   0         0       0         0        0   
28            0     0    0     0   0         0       0         0        0   
29            0     0    0     0   0         0       0         0        0   
30            0     0    0     0   0         0       0         0        0   
31            0     0    0     0   0         0       0         0        0   
32            0     0    0     0   0         0       0         0        0   
33            0     0    0     0   0         0       0         0        0   
34            0     0    0     0   0         0       0         0        0   
35            0     0    0     0   0         0       0         0        0   
36            0     0    0     0   0         0       0         0        0   
37            0     0    0     0   0         0       0         0        0   
38            0     0    0     0   0         0       0         0        0   
39            0     0    0     0   0         0       0         0        0   
40            0     0    0     0   0         0       0         0        0   
41            0     0    0     0   0         0       0         0        0   
42            0     0    0     0   0         0       0         0        0   
43            0     0    0     0   0         0       0         0        0   
44            0     0    0     0   0         0       0         0        0   
45            0     0    0     0   0         0       0         0        0   
46            0     0    0     0   0         0       0         0        0   
47            0     0    0     0   0         0       0         0        0   
48            0     0    0     0   0         0       0         0        0   
49            0     0    0     0   0         0       0         0        0   
50            0     0    0     0   0         0       0         0        0   
51

In [42]:
dt = {'ham':0,'spam':1}

In [43]:
y = y.map(dt)

In [44]:
y

1188    0
3390    0
4709    0
4682    0
3261    0
4477    0
1432    0
1249    0
4611    0
1890    0
5384    0
2569    0
169     0
362     0
3619    0
3653    0
5308    0
2065    0
2888    0
3477    0
3949    0
1259    0
4850    0
4002    0
2056    0
2416    0
2279    0
3184    0
5388    0
1083    0
3317    0
1651    0
4831    0
4277    0
490     0
3531    0
2401    0
553     0
1772    0
639     0
5172    0
2948    0
1245    0
1410    0
1788    0
1396    0
2176    0
1382    0
1982    0
4857    0
902     0
47      0
4855    0
2281    0
1964    0
5089    0
1056    0
960     0
4318    0
940     0
5164    0
38      0
156     0
1260    0
4217    0
807     0
608     0
3208    0
637     0
4225    0
1771    0
450     0
1304    0
2035    0
640     0
369     0
299     0
1248    0
925     0
1806    0
3950    0
4767    0
1403    0
2942    0
1235    0
5389    0
4743    0
4617    0
697     0
2072    0
5369    0
3140    0
199     0
993     0
2423    0
3566    0
1206    0
1373    0
3952    0
3693    0


In [45]:
import numpy as np

In [46]:
y = np.array(y) 

In [47]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [48]:
x.shape , y.shape

((1747, 1700), (1747,))

In [49]:
# train test split
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.15)

In [51]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB

In [53]:
mb = MultinomialNB()

bnb = BernoulliNB()

mb.fit(x_train,y_train)
bnb.fit(x_train,y_train)

BernoulliNB()

In [54]:
bnb.fit(x_train,y_train)

BernoulliNB()

In [56]:
print("traning score",mb.score(x_train,y_train))
print("traning score",mb.score(x_test,y_test))

traning score 0.9602425876010782
traning score 0.935361216730038


In [57]:
print("traning score",bnb.score(x_train,y_train))
print("traning score",bnb.score(x_test,y_test))

traning score 0.9582210242587601
traning score 0.9391634980988594


In [58]:
# logistic regerssion , decision tree and random classifier
import joblib


In [59]:
joblib.dump(bnb,'BNB_project.lb')
joblib.dump(bow,'countvectorizer.lb')

['countvectorizer.lb']

In [61]:
prediction  = bnb.predict(x_test)
prediction[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [62]:
y_test[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [63]:
from sklearn.metrics import confusion_matrix

In [64]:
confusion_matrix(y_test,prediction)

array([[144,   2],
       [ 14, 103]], dtype=int64)